"""empty message

Revision ID: 54419eff1536
Revises: 9c7319caa952
Create Date: 2017-05-27 10:33:49.151126

"""

# revision identifiers, used by Alembic.
revision = '54419eff1536'
down_revision = '9c7319caa952'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'NOW()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'date_created')
    # ### end Alembic commands ###
