"""empty message

Revision ID: 9c7319caa952
Revises: a279c6d85c75
Create Date: 2017-05-26 17:15:59.092242

"""

# revision identifiers, used by Alembic.
revision = '9c7319caa952'
down_revision = 'a279c6d85c75'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'blue_probability')
    op.drop_column('matches', 'red_probability')
    op.add_column('tournaments', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'name')
    op.add_column('matches', sa.Column('red_probability', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('blue_probability', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
