"""empty message

Revision ID: a279c6d85c75
Revises: f5cbe28dd1f0
Create Date: 2017-05-16 09:35:41.972475

"""

# revision identifiers, used by Alembic.
revision = 'a279c6d85c75'
down_revision = 'f5cbe28dd1f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('blue_probability', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('blue_score', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('red_probability', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('red_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'red_score')
    op.drop_column('matches', 'red_probability')
    op.drop_column('matches', 'blue_score')
    op.drop_column('matches', 'blue_probability')
    # ### end Alembic commands ###
