"""empty message

Revision ID: ea95a6d278d8
Revises: 94fc51564d2a
Create Date: 2017-06-28 15:55:12.581923

"""

# revision identifiers, used by Alembic.
revision = 'ea95a6d278d8'
down_revision = '94fc51564d2a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('event_date', sa.DateTime(), server_default=sa.text(u'NOW()'), nullable=True))
    op.add_column('tournaments', sa.Column('region', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'region')
    op.drop_column('tournaments', 'event_date')
    # ### end Alembic commands ###
