"""empty message

Revision ID: f5cbe28dd1f0
Revises: None
Create Date: 2017-05-16 09:33:16.090161

"""

# revision identifiers, used by Alembic.
revision = 'f5cbe28dd1f0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_num', sa.Integer(), nullable=True),
    sa.Column('red1', sa.String(), nullable=True),
    sa.Column('red2', sa.String(), nullable=True),
    sa.Column('blue1', sa.String(), nullable=True),
    sa.Column('blue2', sa.String(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
